# 数据模型模块 - 定义所有API相关的数据模型

# Anthropic模型
from .anthropic import (
    AnthropicContentBlock,
    AnthropicContentTypes,
    AnthropicErrorDetail,
    AnthropicErrorResponse,
    AnthropicMessage,
    # 数据模型
    AnthropicMessageContent,
    AnthropicMessageResponse,
    AnthropicMessageTypes,
    AnthropicPing,
    AnthropicRequest,
    AnthropicRoles,
    # 流式响应相关
    AnthropicStreamContentBlock,
    # 常量类
    AnthropicStreamEventTypes,
    AnthropicSystemMessage,
    AnthropicTextContent,
    AnthropicToolDefinition,
    AnthropicToolUse,
    AnthropicUsage,
    ContentBlock,
    Delta,
)

# 错误模型
from .errors import (
    ERROR_CODE_MAPPING,
    BadRequestError,
    ErrorDetail,
    ExternalServiceError,
    NotFoundError,
    RateLimitError,
    ServerError,
    ServiceUnavailableError,
    StandardErrorResponse,
    TimeoutError,
    UnauthorizedError,
    ValidationError,
    ValidationErrorItem,
    ValidationErrorResponse,
    get_error_response,
)

# OpenAI模型
from .openai import (
    OpenAIChoice,
    OpenAIChoiceDelta,
    OpenAICompletionUsage,
    OpenAIErrorDetail,
    OpenAIErrorResponse,
    OpenAIImageUrl,
    OpenAIMessage,
    OpenAIMessageContent,
    OpenAIRequest,
    OpenAIResponse,
    OpenAIStreamResponse,
    OpenAITool,
    OpenAIToolCall,
    OpenAIToolCallFunction,
    OpenAIToolFunction,
    OpenAIUsage,
)

__all__ = [
    # Anthropic 常量类
    "AnthropicStreamEventTypes",
    "AnthropicContentTypes",
    "AnthropicMessageTypes",
    "AnthropicRoles",
    # Anthropic 数据模型
    "AnthropicMessageContent",
    "AnthropicMessage",
    "AnthropicSystemMessage",
    "AnthropicToolDefinition",
    "AnthropicRequest",
    "AnthropicToolUse",
    "AnthropicTextContent",
    "AnthropicContentBlock",
    "AnthropicUsage",
    "AnthropicMessageResponse",
    "AnthropicErrorDetail",
    "AnthropicErrorResponse",
    "AnthropicPing",
    "AnthropicStreamContentBlock",
    "Delta",
    "ContentBlock",
    # OpenAI
    "OpenAIMessageContent",
    "OpenAIMessage",
    "OpenAIImageUrl",
    "OpenAIToolCallFunction",
    "OpenAIToolCall",
    "OpenAIToolFunction",
    "OpenAITool",
    "OpenAIRequest",
    "OpenAIChoiceDelta",
    "OpenAIChoice",
    "OpenAIUsage",
    "OpenAICompletionUsage",
    "OpenAIResponse",
    "OpenAIStreamResponse",
    "OpenAIErrorDetail",
    "OpenAIErrorResponse",
    # 错误处理
    "ErrorDetail",
    "StandardErrorResponse",
    "ValidationErrorItem",
    "ValidationError",
    "ValidationErrorResponse",
    "UnauthorizedError",
    "RateLimitError",
    "ServerError",
    "TimeoutError",
    "NotFoundError",
    "BadRequestError",
    "ServiceUnavailableError",
    "ExternalServiceError",
    "ERROR_CODE_MAPPING",
    "get_error_response",
]
